# Generated by Django 3.0.4 on 2020-07-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(choices=[('Animels', 'Animels'), ('Safety Hazards', 'Safety Hazards'), ('Car Accident', 'Car Accident'), ('Signpost Damage', 'Signpost Damage'), ('Weather Damage', 'Weather Damage'), ('Other', 'Other')], max_length=200, null=True)),
                ('publication_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('details', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
