# Generated by Django 3.0.4 on 2020-07-18 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='complaint',
        ),
    ]
