# Generated by Django 3.0.4 on 2020-07-18 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_report_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='tags',
            field=models.ManyToManyField(to='accounts.Tag'),
        ),
        migrations.AddField(
            model_name='report',
            name='complaint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Complaint'),
        ),
    ]
