# Generated by Django 3.0.4 on 2020-07-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200718_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='complaint',
        ),
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('Animels', 'Animels'), ('Safety Hazards', 'Safety Hazards'), ('Car Accident', 'Car Accident'), ('Signpost Damage', 'Signpost Damage'), ('Weather Damage', 'Weather Damage'), ('Other', 'Other')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='details',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
