# Generated by Django 3.0.4 on 2020-07-18 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_report_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='category',
        ),
        migrations.RemoveField(
            model_name='report',
            name='details',
        ),
        migrations.RemoveField(
            model_name='report',
            name='location',
        ),
        migrations.RemoveField(
            model_name='report',
            name='name',
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(choices=[('Animels', 'Animels'), ('Safety Hazards', 'Safety Hazards'), ('Car Accident', 'Car Accident'), ('Signpost Damage', 'Signpost Damage'), ('Weather Damage', 'Weather Damage'), ('Other', 'Other')], max_length=200, null=True)),
                ('publication_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('details', models.TextField(blank=True, max_length=200, null=True)),
                ('tags', models.ManyToManyField(to='accounts.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='complaint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Complaint'),
        ),
    ]
