# Generated by Django 3.0.4 on 2020-07-19 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0011_auto_20200719_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='report',
            name='customer',
        ),
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('Animels', 'Animels'), ('Safety Hazards', 'Safety Hazards'), ('Car Accident', 'Car Accident'), ('Signpost Damage', 'Signpost Damage'), ('Weather Damage', 'Weather Damage'), ('Other', 'Other')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='details',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='user_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
