# Generated by Django 3.0.4 on 2020-07-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200719_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='urgency',
            field=models.CharField(choices=[('Immediate', 'Immediate'), ('Medium', 'Medium'), ('Not urgent', 'Not urgent')], max_length=200, null=True),
        ),
    ]
